spring:
  profiles:
    #运行的环境
    active: test
  application:
    name: redis-operate
  redis:
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器端口号
    port: 6379
    # 使用的数据库索引，默认是0
    database: 2
    # 连接超时时间
    timeout: 1800000
    # 设置密码
    password:
    # 连接池 lettuce 的配置
    lettuce:
      pool:
        max-active: 100
        min-idle: 10
        max-wait: 100000
  redisson:
    address: "redis://localhost:6379"